# Generated by Django 4.2.5 on 2023-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(default=0, upload_to='audio/'),
            preserve_default=False,
        ),
    ]
